from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.pdfbase.pdfmetrics import stringWidth
from reportlab.lib.enums import TA_CENTER
import os, csv

root=os.path.dirname(os.path.dirname(os.path.abspath(__file__))); out=os.path.join(root,'reports','HR_Analytics_Report.pdf')
os.makedirs(os.path.dirname(out),exist_ok=True)
with open(os.path.join(root,'data','hr_employee_data.csv'),encoding='utf-8') as f: rows=list(csv.DictReader(f))
n=len(rows); exits=sum(r['attrition']=='Yes' for r in rows); active=sum(r['employment_status']=='Active' for r in rows)
avg=lambda k:sum(float(r[k]) for r in rows)/n
dept={}
for r in rows: dept.setdefault(r['department'],[]).append(r)
styles=getSampleStyleSheet(); styles.add(ParagraphStyle('Title2',parent=styles['Title'],fontName='Helvetica-Bold',fontSize=25,leading=30,textColor=colors.HexColor('#102A43'),spaceAfter=8));styles.add(ParagraphStyle('Sub',parent=styles['Normal'],fontSize=11,leading=16,textColor=colors.HexColor('#627D98')));styles.add(ParagraphStyle('H',parent=styles['Heading2'],fontName='Helvetica-Bold',fontSize=15,leading=19,textColor=colors.HexColor('#102A43'),spaceBefore=12,spaceAfter=8));styles.add(ParagraphStyle('Body2',parent=styles['BodyText'],fontSize=10,leading=15,textColor=colors.HexColor('#334E68'),spaceAfter=7));styles.add(ParagraphStyle('Kpi',parent=styles['Normal'],fontSize=18,leading=22,textColor=colors.HexColor('#1976D2'),alignment=TA_CENTER,fontName='Helvetica-Bold'))
def P(t,s='Body2'): return Paragraph(t,styles[s])
def footer(c,d):
    c.saveState(); c.setStrokeColor(colors.HexColor('#D9E2EC'));c.line(2*cm,1.5*cm,19*cm,1.5*cm);c.setFont('Helvetica',8);c.setFillColor(colors.HexColor('#627D98'));c.drawString(2*cm,1*cm,'HR Analytics Dashboard | Synthetic data for internship submission');c.drawRightString(19*cm,1*cm,f'Page {d.page}');c.restoreState()
doc=SimpleDocTemplate(out,pagesize=A4,rightMargin=2*cm,leftMargin=2*cm,topMargin=2*cm,bottomMargin=2*cm); story=[]
story += [Spacer(1,2.2*cm),P('HR Analytics Report','Title2'),P('Workforce performance, attendance, attrition, compensation, and people insights','Sub'),Spacer(1,.8*cm),P('Project Summary','H'),P('This report accompanies the HR Analytics Dashboard. It demonstrates how HR teams can consolidate employee records into a repeatable decision-making view. All records in this project are synthetic and are included for portfolio and learning purposes only.'),Spacer(1,.3*cm)]
kpis=[['HEADCOUNT','ACTIVE','ATTRITION','AVG ATTENDANCE','AVG PERFORMANCE'],[str(n),str(active),f'{exits/n*100:.1f}%',f'{avg("attendance_pct"):.1f}%',f'{avg("performance_rating"):.2f}/5']]
t=Table(kpis,colWidths=[3.4*cm]*5,rowHeights=[.55*cm,1.1*cm]);t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),colors.HexColor('#EAF2FB')),('TEXTCOLOR',(0,0),(-1,0),colors.HexColor('#486581')),('FONTNAME',(0,0),(-1,0),'Helvetica-Bold'),('FONTSIZE',(0,0),(-1,0),7),('ALIGN',(0,0),(-1,-1),'CENTER'),('FONTNAME',(0,1),(-1,1),'Helvetica-Bold'),('FONTSIZE',(0,1),(-1,1),15),('TEXTCOLOR',(0,1),(-1,1),colors.HexColor('#1976D2')),('GRID',(0,0),(-1,-1),.25,colors.HexColor('#D9E2EC')),('VALIGN',(0,0),(-1,-1),'MIDDLE')]));story += [t,Spacer(1,.6*cm),P('Purpose and Business Questions','H'),P('The dashboard answers five practical HR questions: How is the workforce distributed? Which employee groups show elevated attrition? Where are attendance risks concentrated? Are pay and performance patterns aligned? Which employee segments should be prioritised for action?'),P('Recommended users are HR business partners, talent leaders, and departmental managers. The dashboard should be reviewed monthly, with data-quality checks before executive reporting.'),PageBreak()]
story += [P('Key Findings','H')]
ranking=[]
for d,rs in dept.items(): ranking.append([d,len(rs),sum(r['attrition']=='Yes' for r in rs)/len(rs)*100,avg2:=sum(float(r['attendance_pct']) for r in rs)/len(rs),sum(float(r['monthly_salary']) for r in rs)/len(rs)])
ranking.sort(key=lambda x:x[2],reverse=True)
high=ranking[0]
story += [P(f'<b>1. Retention:</b> The sample has an overall attrition rate of {exits/n*100:.1f}%. <b>{high[0]}</b> has the highest observed departmental rate ({high[2]:.1f}%), signalling a priority for stay interviews and manager review.'),P(f'<b>2. Attendance:</b> Average attendance is {avg("attendance_pct"):.1f}%. Employees below 92% attendance should be reviewed alongside overtime, leave type, workload, and wellbeing context - not treated as a performance conclusion by itself.'),P(f'<b>3. Performance:</b> Average performance is {avg("performance_rating"):.2f} out of 5. The dashboard allows HR to compare performance with engagement, salary, and attendance to target coaching and learning investments.'),P(f'<b>4. Compensation:</b> Average monthly salary is INR {avg("monthly_salary"):,.0f}. Department-level salary ranges provide an initial fairness and market-benchmarking view, but should be supplemented with level, tenure, and location controls.'),P('Department scorecard','H')]
data=[['Department','Headcount','Attrition','Avg attendance','Avg salary (INR)']]+[[x[0],str(x[1]),f'{x[2]:.1f}%',f'{x[3]:.1f}%',f'{x[4]:,.0f}'] for x in ranking]
t=Table(data,colWidths=[4*cm,2.4*cm,2.7*cm,3.4*cm,4.2*cm]);t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),colors.HexColor('#102A43')),('TEXTCOLOR',(0,0),(-1,0),colors.white),('FONTNAME',(0,0),(-1,0),'Helvetica-Bold'),('FONTSIZE',(0,0),(-1,-1),8.5),('GRID',(0,0),(-1,-1),.3,colors.HexColor('#D9E2EC')),('ROWBACKGROUNDS',(0,1),(-1,-1),[colors.white,colors.HexColor('#F7FAFC')]),('ALIGN',(1,1),(-1,-1),'RIGHT'),('VALIGN',(0,0),(-1,-1),'MIDDLE'),('TOPPADDING',(0,0),(-1,-1),7),('BOTTOMPADDING',(0,0),(-1,-1),7)]));story += [t,Spacer(1,.4*cm),P('Interpretation note: the dataset is deliberately small and synthetic; differences illustrate dashboard use and are not statistically generalisable.'),PageBreak()]
story += [P('Recommended Actions','H'),P('<b>Build a retention review cadence.</b> Segment attrition by department, role, tenure, manager, and reason for leaving. Discuss concentrations in a monthly people review and assign owners to action plans.'),P('<b>Use attendance as an early signal, not a punitive metric.</b> Flag groups below the 95% target, then analyse leave patterns, scheduling, workload, and wellbeing. Ensure local policy and employee privacy are respected.'),P('<b>Connect compensation with job architecture.</b> Compare salary by department only after controlling for grade, skills, experience, and geography. Escalate unexplained disparities for pay-equity review.'),P('<b>Make performance conversations developmental.</b> Combine ratings with engagement and training hours. Create targeted learning and manager-coaching actions for teams with lower performance or engagement.'),P('Dashboard Design and Data Model','H'),P('The interactive dashboard uses global filters for department, location, and employment status. KPI cards summarize the selected cohort. Four charts show attrition by department, workforce composition, attendance distribution, and the relationship between salary and performance. The employee table makes records transparent and supports follow-up analysis.'),P('The PostgreSQL-compatible model contains one employee fact table. The included SQL exposes views for workforce KPIs, attrition, attendance risk, salary benchmarking, and a BI-ready employee analytics layer. In production, replace the sample file with secured HRIS, payroll, performance, and attendance sources.'),PageBreak()]
story += [P('Implementation Guide','H'),P('<b>1. Data preparation:</b> validate employee IDs; standardise department and role names; remove duplicate records; derive active/terminated status from approved HR events; and document refresh dates.'),P('<b>2. Power BI / Tableau:</b> import <font name="Courier">data/hr_employee_data.csv</font>. Use the fields in the data dictionary and replicate the included KPI definitions. Create department, location, and status filters. Publish only through approved organizational sharing settings.'),P('<b>3. Governance:</b> limit access to personally identifiable information, apply role-based access, define a metric owner, and suppress very small cohorts in any external reporting. Monitor definitions and refresh exceptions.'),P('Repository Deliverables','H'),P('The GitHub repository contains a runnable browser dashboard, CSS and JavaScript source, synthetic sample data, PostgreSQL schema and query scripts, documentation, and this PDF report. It can be deployed free through GitHub Pages by selecting the main branch and root directory.'),P('Limitations','H'),P('This prototype does not include employee names, manager hierarchy, exit reasons, absence categories, grade, or historical monthly snapshots. These should be added to a real implementation after HR policy, consent, security, and metric governance have been agreed.'),Spacer(1,.8*cm),P('Prepared for internship project submission','Sub')]
doc.build(story,onFirstPage=footer,onLaterPages=footer);print(out)
